server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: application
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379
      ssl:
        enabled: false
      password: P@ssword
      timeout: 1000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always